export PATH=/usr/local/bin:$PATH
alias gdiff='git diff'
alias gst='git status'
alias gb='git branch'
alias gp='git pull'
alias mvjet='mvn jetty:deploy-war'
alias mvcli='mvn clean install'
#alias gsr='git svn rebase'
#alias gsc='git svn dcommit'
alias ..='cd ..'
alias ....='cd ../..'
#alias gl='git log --pretty=oneline --abbrev-commit --decorate'
alias gl='git log --branches --remotes --tags --graph --oneline --decorate'
alias gg='git log --graph --abbrev-commit --decorate --date=relative --all'
source ~/.profile
